/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      maxWidth: {
        editorial: "1400px",
      },
      fontFamily: {
        display: ["var(--font-display)", "Georgia", "serif"],
        body: [
          "var(--font-geist-sans)",
          "Geist",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        sans: [
          "var(--font-geist-sans)",
          "Geist",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        serif: ["var(--font-serif)", "Cormorant Garamond", "Georgia", "serif"],
      },
      colors: {
        paper: "var(--paper)",
        ink: "var(--ink)",
        copper: {
          DEFAULT: "var(--copper)",
          soft: "var(--copper-soft)",
        },
        rule: "var(--rule)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        surface: "var(--surface)",
        border: "var(--border)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          50: "#fafee7",
          100: "#f3fccb",
          200: "#e5f99d",
          300: "#d1f264",
          400: "#bee740",
          500: "#9ccc16",
          600: "#79a30d",
          700: "#5b7c0f",
          800: "#4a6212",
          900: "#3e5314",
          950: "#1f2e05",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          50: "#f5f2ff",
          100: "#ede8ff",
          200: "#dcd4ff",
          300: "#c3b1ff",
          400: "#a784ff",
          500: "#8c52ff",
          600: "#7e2ff8",
          700: "#701de4",
          800: "#661ad1",
          900: "#4d169c",
          950: "#2e0b6a",
        },
        neutral: {
          50: "#f9f8f6",
          100: "#f3f0ea",
          200: "#e8e3db",
          300: "#d0c9bd",
          400: "#a39b90",
          500: "#6b6560",
          600: "#4a4540",
          700: "#322e2a",
          800: "#1c1915",
          900: "#181818",
          950: "#141210",
        },
        ring: "var(--ring)",
        destructive: "var(--destructive)",
      },
      letterSpacing: {
        label: "0.14em",
        widest: "0.15em",
      },
      keyframes: {
        editorialFade: {
          from: { opacity: 0, transform: "translateY(10px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        slideUpAndFade: {
          from: { opacity: 0, transform: "translateY(2px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        staggerUp: {
          from: { opacity: 0, transform: "translateY(14px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: {
        editorialFade:
          "editorialFade 700ms cubic-bezier(0.22, 1, 0.36, 1) both",
        slideUpAndFade: "slideUpAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)",
        staggerUp: "staggerUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  darkMode: "class",
  plugins: [],
};
