// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IAuthorFields {
  /** Title */
  title: string

  /** Description */
  description?: Document | undefined
}

/** Resumé / About Author */

export interface IAuthor extends Entry<IAuthorFields> {
  contentTypeId: 'author'
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'author'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IEducationFields {
  /** title */
  title: string

  /** Description */
  description: string

  /** StartYear */
  startYear: string

  /** EndDate */
  endDate?: string | undefined

  /** mainFrameworks */
  mainFrameworks: string

  /** finished */
  finished: boolean
}

/** Courses or degrees taken */

export interface IEducation extends Entry<IEducationFields> {
  contentTypeId: 'education'
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'education'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IExperienceFields {
  /** title */
  title: string

  /** Description */
  description: string

  /** StartYear */
  startYear: string

  /** EndDate */
  endDate?: string | undefined

  /** finished */
  finished: boolean

  /** position */
  position: string
}

/** Work Experience Item */

export interface IExperience extends Entry<IExperienceFields> {
  contentTypeId: 'experience'
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'experience'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IJobTypesFields {
  /** Job */
  job: string

  /** Job Description */
  jobDescription: string
}

/** Current job types I can peform */

export interface IJobTypes extends Entry<IJobTypesFields> {
  contentTypeId: 'jobTypes'
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'jobTypes'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IProjectFields {
  /** Project Name */
  projectName: string

  /** Featured_media */
  featuredMedia: Asset

  /** project description */
  projectDescription?: Document | undefined

  /** Category */
  category: 'Web' | 'All' | 'Mobile'

  /** link */
  link: string

  /** date */
  date: string
}

/** A project portifolio */

export interface IProject extends Entry<IProjectFields> {
  contentTypeId: 'project'
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'project'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'author'
  | 'education'
  | 'experience'
  | 'jobTypes'
  | 'project'

export type IEntry = IAuthor | IEducation | IExperience | IJobTypes | IProject

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
