// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAuthorFields {
  /** Title */
  title: string;

  /** Description */
  description?: Document | undefined;
}

/** Resumé / About Author */

export interface IAuthor extends Entry<IAuthorFields> {
  categoryTypeId: "author";
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IJobTypesFields {
  /** Job */
  job: string;

  /** Job Description */
  jobDescription: string;
}

/** Current job types I can peform */

export interface IJobTypes extends Entry<IJobTypesFields> {
  categoryTypeId: "jobTypes";
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "jobTypes";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectFields {
  /** Project Name */
  projectName: string;

  /** Featured_media */
  featuredMedia: Asset;

  /** project description */
  projectDescription?: Document | undefined;

  /** Category */
  category: "Web" | "All" | "Mobile";
}

/** A project portifolio */

export interface IProject extends Entry<IProjectFields> {
  categoryTypeId: "project";
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "project";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "author" | "jobTypes" | "project";

export type IEntry = IAuthor | IJobTypes | IProject;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
